sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2 
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/ebooklib.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git

- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt
- asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
- git clone https://github.com/gitenberg-dev/HTMLBook

# make book.html available to jinja2 environment by putting it into templates
- cp book.html asciidoctor-htmlbook/gitberg-machine/templates/

- /usr/bin/python asciidoctor-htmlbook/gitberg-machine/machine.py -o . -m metadata.yaml book.html
- xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl book.html
- cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
- if [ -e cover.jpg ]; then cp cover.jpg OEBPS/cover.jpg; fi
# look for first images directory and one found, copy over to ./OEBPS
- find . -name images -type d | head -n 1 | xargs -I {} mv {} ./OEBPS/
- zip -rX book.epub mimetype
- zip -rX book.epub OEBPS/ META-INF/
- if test -d "OEBPS/images/"; then zip -rX book.epub OEBPS/images/ ;fi
- mv book.epub The-Idiot.epub
- ebook-convert The-Idiot.epub The-Idiot.mobi
- xvfb-run ebook-convert The-Idiot.epub The-Idiot.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: aU6fbyCFQ/AneFjK/cUUVyiCfIUjE4VgcAcC7Va+RD2C2CzkWn8u3VhowBPezXWi4y//8nowZFaaEQENgAUzkF2EiVhf4eImnNuW2TU0/ITPgNk24vVOqGcuvIN//gTLM2Mgk3GVcRvxX0KKln4+5Z4G+821GL+KXJyuw6Tge/znTNPtUT5T+rusq4mzzb0jD6fJVcAMc/VFsVmBkPIkgRs13XJObNUhp+IUC1bm/q1BMRpe94G/ztFmVHiWDJiM7YWxISF+9RxWkFWYjohdWgVzSvI8lG2L166MJMqr8OsHZyRhS1uQ9LhZ1N8g9YYQyv61oXeW7mmU8WlglV6fMrJQ25N7nE5xWktxQ/0w8g/ICr5WRDadXkmEulLpzvrbJhI0+CLQdYKiHWfzd/oANkMcUblrcDZ3LsBSZAzAUpTgNOOeDajKzkEJmv97MCwo0+g7CbeiHCjUdlP8KyEJNB2dIH+l1OJ8QSMC0rhtQAMLsMGW0PD8prIAudYEkYJp/i6Nz6EijWSxbbxu5nAgjVrt22emBGG7NpLRi6SKlGHAonx9z5uRVoC002fbgL+rr8hDLQa0T6Zer5YDz3p735Hvm2FqQndmiyonRBlp8iWX1s+NhhyLDO/1OpLFt0MriMj+K4X+xxwOUcdOFNY0ylL5WLePs/KuY7JeeObI5Ks=
  file:
    - The-Idiot.epub
    - The-Idiot.mobi
    - The-Idiot.pdf
  "on":
    repo: GITenberg/The-Idiot_2638
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre